<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <LangVersion>latest</LangVersion>
        <PlatformTarget>x64</PlatformTarget>
        <ImplicitUsings>true</ImplicitUsings>
        <PublishAddinFiles>true</PublishAddinFiles>
        <Configurations>Debug R20;Debug R21;Debug R22;Debug R23;Debug R24;Debug R25</Configurations>
        <Configurations>$(Configurations);Release R20;Release R21;Release R22;Release R23;Release R24;Release R25</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('R20'))">
        <RevitVersion>2020</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R21'))">
        <RevitVersion>2021</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R22'))">
        <RevitVersion>2022</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R23'))">
        <RevitVersion>2023</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R24'))">
        <RevitVersion>2024</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R25'))">
        <RevitVersion>2025</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup>
        <StartAction>Program</StartAction>
        <StartProgram>C:\Program Files\Autodesk\Revit $(RevitVersion)\Revit.exe</StartProgram>
        <StartArguments>/language RUS</StartArguments>
    </PropertyGroup>

        

    <ItemGroup>
        <PackageReference Include="MaterialDesignColors" Version="5.2.2-ci891" />
        <PackageReference Include="MaterialDesignExtensions" Version="3.3.0" />
        <PackageReference Include="MaterialDesignThemes" Version="5.2.*" />
        <PackageReference Include="MaterialDesignThemes.MahApps" Version="3.1.1-ci691" />
        <PackageReference Include="MaterialDesignThemes.MahApps.163" Version="0.0.111" />
        <PackageReference Include="MaterialDesignThemes.Wpf" Version="1.0.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Nice3point.Revit.Build.Tasks" Version="2.*" />
        <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Extensions" Version="$(RevitVersion).*-*" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
        <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
        <PackageReference Include="Revit.AdWindows.x64" Version="2023.0.0" />
        <PackageReference Include="Revit.IFC.IFCExportUIOverride" Version="$(RevitVersion).*" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Autodesk.Revit.DB" />
        <Using Include="Nice3point.Revit.Extensions" />
        <Using Include="JetBrains.Annotations" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\Icons\SystemName.png" />
        <Resource Include="Resources\Icons\ActiveView.png" />
        <Resource Include="Resources\Icons\FamilyManager.png" />
        <Resource Include="Resources\Icons\ai.png" />
        <Resource Include="Resources\Icons\ImportExcel.png" />
        <Resource Include="Resources\Icons\ExportModels.png" />
        <Resource Include="Resources\Icons\intersector.png" />
        <Resource Include="Resources\Icons\ViewManager.png" />
        <Resource Include="Resources\Icons\LevelByFloor.png" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\ActiveView\ActiveView.csproj" />
      <ProjectReference Include="..\ChatGPT\ChatGPT.csproj" />
      <ProjectReference Include="..\ColorsByParameters\ColorsByParameters.csproj" />
      <ProjectReference Include="..\EngineeringSystems\EngineeringSystems.csproj" />
      <ProjectReference Include="..\ExporterModels\ExporterModels.csproj" />
      <ProjectReference Include="..\FamilyCleaner\FamilyCleaner.csproj" />
      <ProjectReference Include="..\FsmModules\FsmModules.csproj" />
      <ProjectReference Include="..\ImportExcelByParameter\ImportExcelByParameter.csproj" />
      <ProjectReference Include="..\LevelByFloor\LevelByFloor.csproj" />
      <ProjectReference Include="..\SolidIntersection\SolidIntersection.csproj" />
      <ProjectReference Include="..\SystemName\SystemName.csproj" />
      <ProjectReference Include="..\ViewManager\ViewManager.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="ViewModels\MepGeneral\" />
      <Folder Include="Views\MepGeneral\" />
    </ItemGroup>
    
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="if not exist &quot;$(TargetDir)config&quot; mkdir &quot;$(TargetDir)config&quot;&#xA;echo {} &gt; &quot;$(TargetDir)config\config.json&quot;&#xA;echo {} &gt; &quot;$(TargetDir)config\Projects.json&quot;" />
    </Target>
</Project>